### ISSUE TITLE
Is the Chromium dev team aware?

### ISSUE THREAD

**Issue by birdie-github** [z0ccc/extension-fingerprints#1]
Have you contacted them and reported this?

It surely looks like a serious privacy related vulnerability.

**Comment by z0ccc** [comment]
Ya they know

**Comment by networkException** [comment]
Is there an issue in their bug tracker or something else you can link?

**Comment by ajayyy** [comment]
@networkException Manifest v3 allows you to restrict web accessible resources to specific domains, but that still doesn't solve the issue for extensions that need the resource on all pages.
