### ISSUE TITLE
Don't know how you detect "Google Play Book". I don't have this extension!

### ISSUE THREAD

**Issue by verdy-p** [z0ccc/extension-fingerprints#2]
Fake detection of "Google Play Book" on my PC. I don't have thazt extension at all (it may have been installed by default with Google Play, but it is no longer present since long, and I've never used it and it does not show in "extensions" or "apps".

Note that this is on my PC. If this is caused by the fact that it is preinstalled on my Android smartphone (and I cannot remove it, just disable it in Android), then there's some internal hidden communication via Google Servers and we should know how to disable it (and it is illegal). And it would be even more dangerous if a web site can target may smartphone via my PC, or the reverse.

Or there's a severe bbug in the Google's "IBA Optout", so that Google abuses our rights and does not tell the truth with its browser or with out user accounts (even if Google promised to change things related to the RGPD, this may also be faked).

**Comment by z0ccc** [comment]
Hmm very strange. It could definitely have just been a bug. Does it get detected every time to load the website?
