### ISSUE TITLE
Can you add detection for tampermonkey?

### ISSUE THREAD

**Issue by xuemingyang** [z0ccc/extension-fingerprints#3]
Tampermonkey is also a popular plug-in library, can u add it to your detection, the extension address is: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en-US

**Comment by z0ccc** [comment]
Tamper monkey cannot be detected using this method because they do not use web accessible resources.
